/*
 * @Author: your name
 * @Date: 2020-03-08 16:42:49
 * @LastEditTime: 2020-03-08 18:53:32
 * @LastEditors: Please set LastEditors
 * @Description: In User Settings Edit
 * @FilePath: \lsp-sample\server\syntaxes\DevUIhtmlSyntaxes.ts
 */
import {
	CompletionItemKind,
} from 'vscode-languageserver';
export const DevUIhtmlSyntaxes=[
	{
		label: 'd-accordion',
		kind: CompletionItemKind.Property,
		insertText: '<d-accordion>\n</d-accordion>',
		data: 'accordion',
		sortText: 'daccordion',
		},
		{
		label: 'd-alert',
		kind: CompletionItemKind.Property,
		insertText: '<d-alert>\n</d-alert>',
		data: 'alert',
		sortText: 'dalert',
		},
		{
		label: 'd-anchor',
		kind: CompletionItemKind.Property,
		insertText: '<d-anchor>\n</d-anchor>',
		data: 'anchor',
		sortText: 'danchor',
		},
		{
		label: 'd-auto-complete',
		kind: CompletionItemKind.Property,
		insertText: '<d-auto-complete>\n</d-auto-complete>',
		data: 'auto-complete',
		sortText: 'dauto-complete',
		},
		{
		label: 'd-bundles',
		kind: CompletionItemKind.Property,
		insertText: '<d-bundles>\n</d-bundles>',
		data: 'bundles',
		sortText: 'dbundles',
		},
		{
		label: 'd-button',
		kind: CompletionItemKind.Property,
		insertText: '<d-button>\n</d-button>',
		data: 'button',
		sortText: 'dbutton',
		},
		{
		label: 'd-checkbox',
		kind: CompletionItemKind.Property,
		insertText: '<d-checkbox>\n</d-checkbox>',
		data: 'checkbox',
		sortText: 'dcheckbox',
		},
		{
		label: 'd-common',
		kind: CompletionItemKind.Property,
		insertText: '<d-common>\n</d-common>',
		data: 'common',
		sortText: 'dcommon',
		},
		{
		label: 'd-data-table',
		kind: CompletionItemKind.Property,
		insertText: '<d-data-table>\n</d-data-table>',
		data: 'data-table',
		sortText: 'ddata-table',
		},
		{
		label: 'd-datepicker',
		kind: CompletionItemKind.Property,
		insertText: '<d-datepicker>\n</d-datepicker>',
		data: 'datepicker',
		sortText: 'ddatepicker',
		},
		{
		label: 'd-devui.config',
		kind: CompletionItemKind.Property,
		insertText: '<d-devui.config>\n</d-devui.config>',
		data: 'devui.config',
		sortText: 'ddevui.config',
		},
		{
		label: 'd-devui.css',
		kind: CompletionItemKind.Property,
		insertText: '<d-devui.css>\n</d-devui.css>',
		data: 'devui.css',
		sortText: 'ddevui.css',
		},
		{
		label: 'd-devui.min.css',
		kind: CompletionItemKind.Property,
		insertText: '<d-devui.min.css>\n</d-devui.min.css>',
		data: 'devui.min.css',
		sortText: 'ddevui.min.css',
		},
		{
		label: 'd-devui.module.d.ts',
		kind: CompletionItemKind.Property,
		insertText: '<d-devui.module.d.ts>\n</d-devui.module.d.ts>',
		data: 'devui.module.d.ts',
		sortText: 'ddevui.module.d.ts',
		},
		{
		label: 'd-dragdrop',
		kind: CompletionItemKind.Property,
		insertText: '<d-dragdrop>\n</d-dragdrop>',
		data: 'dragdrop',
		sortText: 'ddragdrop',
		},
		{
		label: 'd-drawer',
		kind: CompletionItemKind.Property,
		insertText: '<d-drawer>\n</d-drawer>',
		data: 'drawer',
		sortText: 'ddrawer',
		},
		{
		label: 'd-dropdown',
		kind: CompletionItemKind.Property,
		insertText: '<d-dropdown>\n</d-dropdown>',
		data: 'dropdown',
		sortText: 'ddropdown',
		},
		{
		label: 'd-editable-select',
		kind: CompletionItemKind.Property,
		insertText: '<d-editable-select>\n</d-editable-select>',
		data: 'editable-select',
		sortText: 'deditable-select',
		},
		{
		label: 'd-esm2015',
		kind: CompletionItemKind.Property,
		insertText: '<d-esm2015>\n</d-esm2015>',
		data: 'esm2015',
		sortText: 'desm2015',
		},
		{
		label: 'd-esm5',
		kind: CompletionItemKind.Property,
		insertText: '<d-esm5>\n</d-esm5>',
		data: 'esm5',
		sortText: 'desm5',
		},
		{
		label: 'd-fesm2015',
		kind: CompletionItemKind.Property,
		insertText: '<d-fesm2015>\n</d-fesm2015>',
		data: 'fesm2015',
		sortText: 'dfesm2015',
		},
		{
		label: 'd-fesm5',
		kind: CompletionItemKind.Property,
		insertText: '<d-fesm5>\n</d-fesm5>',
		data: 'fesm5',
		sortText: 'dfesm5',
		},
		{
		label: 'd-index.d.ts',
		kind: CompletionItemKind.Property,
		insertText: '<d-index.d.ts>\n</d-index.d.ts>',
		data: 'index.d.ts',
		sortText: 'dindex.d.ts',
		},
		{
		label: 'd-input-number',
		kind: CompletionItemKind.Property,
		insertText: '<d-input-number>\n</d-input-number>',
		data: 'input-number',
		sortText: 'dinput-number',
		},
		{
		label: 'd-LICENSE',
		kind: CompletionItemKind.Property,
		insertText: '<d-LICENSE>\n</d-LICENSE>',
		data: 'LICENSE',
		sortText: 'dLICENSE',
		},
		{
		label: 'd-loading',
		kind: CompletionItemKind.Property,
		insertText: '<d-loading>\n</d-loading>',
		data: 'loading',
		sortText: 'dloading',
		},
		{
		label: 'd-modal',
		kind: CompletionItemKind.Property,
		insertText: '<d-modal>\n</d-modal>',
		data: 'modal',
		sortText: 'dmodal',
		},
		{
		label: 'd-ng-devui.d.ts',
		kind: CompletionItemKind.Property,
		insertText: '<d-ng-devui.d.ts>\n</d-ng-devui.d.ts>',
		data: 'ng-devui.d.ts',
		sortText: 'dng-devui.d.ts',
		},
		{
		label: 'd-ng-devui.metadata.json',
		kind: CompletionItemKind.Property,
		insertText: '<d-ng-devui.metadata.json>\n</d-ng-devui.metadata.json>',
		data: 'ng-devui.metadata.json',
		sortText: 'dng-devui.metadata.json',
		},
		{
		label: 'd-overlay-container',
		kind: CompletionItemKind.Property,
		insertText: '<d-overlay-container>\n</d-overlay-container>',
		data: 'overlay-container',
		sortText: 'doverlay-container',
		},
		{
		label: 'd-package.json',
		kind: CompletionItemKind.Property,
		insertText: '<d-package.json>\n</d-package.json>',
		data: 'package.json',
		sortText: 'dpackage.json',
		},
		{
		label: 'd-pagination',
		kind: CompletionItemKind.Property,
		insertText: '<d-pagination>\n</d-pagination>',
		data: 'pagination',
		sortText: 'dpagination',
		},
		{
		label: 'd-panel',
		kind: CompletionItemKind.Property,
		insertText: '<d-panel>\n</d-panel>',
		data: 'panel',
		sortText: 'dpanel',
		},
		{
		label: 'd-popover',
		kind: CompletionItemKind.Property,
		insertText: '<d-popover>\n</d-popover>',
		data: 'popover',
		sortText: 'dpopover',
		},
		{
		label: 'd-portal',
		kind: CompletionItemKind.Property,
		insertText: '<d-portal>\n</d-portal>',
		data: 'portal',
		sortText: 'dportal',
		},
		{
		label: 'd-position',
		kind: CompletionItemKind.Property,
		insertText: '<d-position>\n</d-position>',
		data: 'position',
		sortText: 'dposition',
		},
		{
		label: 'd-progress',
		kind: CompletionItemKind.Property,
		insertText: '<d-progress>\n</d-progress>',
		data: 'progress',
		sortText: 'dprogress',
		},
		{
		label: 'd-radio',
		kind: CompletionItemKind.Property,
		insertText: '<d-radio>\n</d-radio>',
		data: 'radio',
		sortText: 'dradio',
		},
		{
		label: 'd-README.md',
		kind: CompletionItemKind.Property,
		insertText: '<d-README.md>\n</d-README.md>',
		data: 'README.md',
		sortText: 'dREADME.md',
		},
		{
		label: 'd-search',
		kind: CompletionItemKind.Property,
		insertText: '<d-search>\n</d-search>',
		data: 'search',
		sortText: 'dsearch',
		},
		{
		label: 'd-select',
		kind: CompletionItemKind.Property,
		insertText: '<d-select>\n</d-select>',
		data: 'select',
		sortText: 'dselect',
		},
		{
		label: 'd-slider',
		kind: CompletionItemKind.Property,
		insertText: '<d-slider>\n</d-slider>',
		data: 'slider',
		sortText: 'dslider',
		},
		{
		label: 'd-status',
		kind: CompletionItemKind.Property,
		insertText: '<d-status>\n</d-status>',
		data: 'status',
		sortText: 'dstatus',
		},
		{
		label: 'd-sticky',
		kind: CompletionItemKind.Property,
		insertText: '<d-sticky>\n</d-sticky>',
		data: 'sticky',
		sortText: 'dsticky',
		},
		{
		label: 'd-tabs',
		kind: CompletionItemKind.Property,
		insertText: '<d-tabs>\n</d-tabs>',
		data: 'tabs',
		sortText: 'dtabs',
		},
		{
		label: 'd-tags',
		kind: CompletionItemKind.Property,
		insertText: '<d-tags>\n</d-tags>',
		data: 'tags',
		sortText: 'dtags',
		},
		{
		label: 'd-tags-input',
		kind: CompletionItemKind.Property,
		insertText: '<d-tags-input>\n</d-tags-input>',
		data: 'tags-input',
		sortText: 'dtags-input',
		},
		{
		label: 'd-toast',
		kind: CompletionItemKind.Property,
		insertText: '<d-toast>\n</d-toast>',
		data: 'toast',
		sortText: 'dtoast',
		},
		{
		label: 'd-toggle',
		kind: CompletionItemKind.Property,
		insertText: '<d-toggle>\n</d-toggle>',
		data: 'toggle',
		sortText: 'dtoggle',
		},
		{
		label: 'd-tooltip',
		kind: CompletionItemKind.Property,
		insertText: '<d-tooltip>\n</d-tooltip>',
		data: 'tooltip',
		sortText: 'dtooltip',
		},
		{
		label: 'd-tree',
		kind: CompletionItemKind.Property,
		insertText: '<d-tree>\n</d-tree>',
		data: 'tree',
		sortText: 'dtree',
		},
		{
		label: 'd-tree-select',
		kind: CompletionItemKind.Property,
		insertText: '<d-tree-select>\n</d-tree-select>',
		data: 'tree-select',
		sortText: 'dtree-select',
		},
		{
		label: 'd-upload',
		kind: CompletionItemKind.Property,
		insertText: '<d-upload>\n</d-upload>',
		data: 'upload',
		sortText: 'dupload',
		},
		{
		label: 'd-utils',
		kind: CompletionItemKind.Property,
		insertText: '<d-utils>\n</d-utils>',
		data: 'utils',
		sortText: 'dutils',
		},
		{
		label: 'd-version.d.ts',
		kind: CompletionItemKind.Property,
		insertText: '<d-version.d.ts>\n</d-version.d.ts>',
		data: 'version.d.ts',
		sortText: 'dversion.d.ts',
		},
		{
		label: 'd-window-ref',
		kind: CompletionItemKind.Property,
		insertText: '<d-window-ref>\n</d-window-ref>',
		data: 'window-ref',
		sortText: 'dwindow-ref',
		},		
		
];
